
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: team02-f23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjg3MDUzMjc1","is_bot":false,"login":"hancheng-li","name":""},"headRefName":"Hancheng-MenuItemReview-Get","number":60,"title":"GET endpoint added","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-2/pull/60"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsb-org-put","number":59,"title":"Added put and tests in ucsb org","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-2/pull/59"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsb-org-delete","number":58,"title":"Added delete and tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-2/pull/58"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsb-org-get","number":57,"title":"Added UCSB org get and tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-2/pull/57"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsb-org-controller","number":56,"title":"Added UCSB org controller and tests for get all and post","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-2/pull/56"},{"author":{"id":"U_kgDOBh9GEw","is_bot":false,"login":"ChinDandekar","name":"ChinDandekar"},"headRefName":"chinmay-Dining","number":54,"title":"Added delete endpoint for UCSBDiningCommonsMenuItemsController","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-2/pull/54"},{"author":{"id":"U_kgDOBtX_Tw","is_bot":false,"login":"bradenc24","name":""},"headRefName":"Braden-HelpRequestTable-GetShowEndpoint","number":52,"title":"Adding GET (show) endpoint (get a single help request) and its tests to HelpRequest Controller","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-2/pull/52"}]
