
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: team02-f23-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBh9GEw","is_bot":false,"login":"ChinDandekar","name":"ChinDandekar"},"headRefName":"chinmay-Dining","number":47,"title":"Added Controller for UCSBDiningCommonsMenuItems and tests for controller","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-2/pull/47"},{"author":{"id":"U_kgDOBtX_Tw","is_bot":false,"login":"bradenc24","name":""},"headRefName":"Braden-HelpRequestTable-Controller","number":46,"title":"Create HelpRequest Controller, add GET (index) and POST (create) methods ","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-2/pull/46"}]
